### ISSUE TITLE
Sometimes it does not work

### ISSUE THREAD

**Issue by phar1no** [legendar/chrome-extensions#20]
For example the word approaching on page http://aix4admins.blogspot.ru/2011/09/vmstat-t-5-3-shows-3-statistics-in-5.html
![dad](https://f.cloud.github.com/assets/5820781/1570804/ed88ad92-50f5-11e3-8984-813671dfea28.PNG)

**Comment by legendar** [comment]
The Quick-Translate extension working correctly on that page.
